In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df =  pd.read_csv('/Users/harrilan/Desktop/school/2024 Fall/BA305/project/tn_nashville_2020_04_01.csv')

/var/folders/m2/b_qd00912hg07bdfxg73hd3h0000gn/T/ipykernel_9369/2214966648.py:1: DtypeWarning: Columns (6,8,15,16,17,22,23,24,25,29,30,31,32,33,35,36,37,38,40,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df =  pd.read_csv('/Users/harrilan/Desktop/school/2024 Fall/BA305/project/tn_nashville_2020_04_01.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3092351 entries, 0 to 3092350
Data columns (total 42 columns):
 #   Column                          Dtype
---  ------                          -----
 0   raw_row_number                  object
 1   date                            object
 2   time                            object
 3   location                        object
 4   lat                             float64
 5   lng                             float64
 6   precinct                        object
 7   reporting_area                  float64
 8   zone                            object
 9   subject_age                     float64
 10  subject_race                    object
 11  subject_sex                     object
 12  officer_id_hash                 object
 13  type                            object
 14  violation                       object
 15  arrest_made                     object
 16  citation_issued                 object
 17  warning_issued                  object
 18  outcome                         object
 19  contraband_found                object
 20  contraband_drugs                object
 21  contraband_weapons              object
 22  frisk_performed                 object
 23  search_conducted                object
 24  search_person                   object
 25  search_vehicle                  object
 26  search_basis                    object
 27  reason_for_stop                 object
 28  vehicle_registration_state      object
 29  notes                           object
 30  raw_verbal_warning_issued       object
 31  raw_written_warning_issued      object
 32  raw_traffic_citation_issued     object
 33  raw_misd_state_citation_issued  object
 34  raw_suspect_ethnicity           object
 35  raw_driver_searched             object
 36  raw_passenger_searched          object
 37  raw_search_consent              object
 38  raw_search_arrest               object
 39  raw_search_warrant              bool
 40  raw_search_inventory            object
 41  raw_search_plain_view           object
dtypes: bool(1), float64(4), object(37)
memory usage: 970.3+ MB

In [5]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
df.head()

,raw_row_number,date,time,location,lat,lng,precinct,reporting_area,zone,subject_age,subject_race,subject_sex,officer_id_hash,type,violation,arrest_made,citation_issued,warning_issued,outcome,contraband_found,contraband_drugs,contraband_weapons,frisk_performed,search_conducted,search_person,search_vehicle,search_basis,reason_for_stop,vehicle_registration_state,notes,raw_verbal_warning_issued,raw_written_warning_issued,raw_traffic_citation_issued,raw_misd_state_citation_issued,raw_suspect_ethnicity,raw_driver_searched,raw_passenger_searched,raw_search_consent,raw_search_arrest,raw_search_warrant,raw_search_inventory,raw_search_plain_view
0,232947,2010-10-10,NaN,"DOMINICAN DR & ROSA L PARKS BLVD, NASHVILLE, T...",36.187925,-86.798519,6.0,4403.0,611.0,27.0,black,male,80ed1b32eb,vehicular,investigative stop,False,False,True,warning,NaN,NaN,NaN,False,False,False,False,NaN,investigative stop,TN,NaN,True,False,False,NaN,N,False,False,False,False,False,False,False
1,237161,2010-10-10,10:00:00,"1122 LEBANON PIKE, NASHVILLE, TN, 37210",36.155521,-86.735902,5.0,9035.0,513.0,18.0,white,male,a983204b21,vehicular,moving traffic violation,False,True,False,citation,NaN,NaN,NaN,False,False,False,False,NaN,moving traffic violation,TN,NaN,False,False,True,NaN,N,False,False,False,False,False,False,False
2,232902,2010-10-10,10:00:00,"898 DAVIDSON DR, , TN, 37205",36.117420,-86.895593,1.0,5005.0,121.0,52.0,white,male,f5d8fbd78b,vehicular,vehicle equipment violation,False,False,True,warning,NaN,NaN,NaN,False,False,False,False,NaN,vehicle equipment violation,TN,NaN,True,False,False,NaN,N,False,False,False,False,False,False,False
3,233219,2010-10-10,22:00:00,"MURFREESBORO PIKE & NASHBORO BLVD, ANTIOCH, TN...",36.086799,-86.648581,3.0,8891.0,325.0,25.0,white,male,4f1d028e45,vehicular,registration,False,False,True,warning,NaN,NaN,NaN,False,False,False,False,NaN,registration,TN,NaN,True,False,False,NaN,N,False,False,False,False,False,False,False
4,232780,2010-10-10,01:00:00,"BUCHANAN ST, NORTH, TN, 37208",36.180038,-86.809109,NaN,NaN,NaN,21.0,black,male,0f0e6b7d67,vehicular,vehicle equipment violation,False,False,True,warning,False,False,False,False,True,True,True,probable cause,vehicle equipment violation,TN,NaN,True,False,False,NaN,N,True,True,False,False,False,False,False

In [ ]:
df_dropped = df.drop(columns=[
    'age_group', 
    ])